<?php

class CountryTableSeeder extends Seeder {
    //ISO 3166-1 alpha-3
    public function run(){

        DB::table('country')->delete();

        Country::create(array('code' => 'ABW', 'label' => 'Aruba'));
        Country::create(array('code' => 'AFG', 'label' => 'Afghanistan'));
        Country::create(array('code' => 'AGO', 'label' => 'Angola'));
        Country::create(array('code' => 'AIA', 'label' => 'Anguilla'));
        Country::create(array('code' => 'ALA', 'label' => 'Åland Islands'));
        Country::create(array('code' => 'ALB', 'label' => 'Albania'));
        Country::create(array('code' => 'AND', 'label' => 'Andorra'));
        Country::create(array('code' => 'ARE', 'label' => 'United Arab Emirates'));
        Country::create(array('code' => 'ARG', 'label' => 'Argentina'));
        Country::create(array('code' => 'ARM', 'label' => 'Armenia'));
        Country::create(array('code' => 'ASM', 'label' => 'American Samoa'));
        Country::create(array('code' => 'ATA', 'label' => 'Antarctica'));
        Country::create(array('code' => 'ATF', 'label' => 'French Southern Territories'));
        Country::create(array('code' => 'ATG', 'label' => 'Antigua and Barbuda'));
        Country::create(array('code' => 'AUS', 'label' => 'Australia'));
        Country::create(array('code' => 'AUT', 'label' => 'Austria'));
        Country::create(array('code' => 'AZE', 'label' => 'Azerbaijan'));
        Country::create(array('code' => 'BDI', 'label' => 'Burundi'));
        Country::create(array('code' => 'BEL', 'label' => 'Belgium'));
        Country::create(array('code' => 'BEN', 'label' => 'Benin'));
        Country::create(array('code' => 'BES', 'label' => 'Bonaire, Sint Eustatius and Saba'));
        Country::create(array('code' => 'BFA', 'label' => 'Burkina Faso'));
        Country::create(array('code' => 'BGD', 'label' => 'Bangladesh'));
        Country::create(array('code' => 'BGR', 'label' => 'Bulgaria'));
        Country::create(array('code' => 'BHR', 'label' => 'Bahrain'));
        Country::create(array('code' => 'BHS', 'label' => 'Bahamas'));
        Country::create(array('code' => 'BIH', 'label' => 'Bosnia and Herzegovina'));
        Country::create(array('code' => 'BLM', 'label' => 'Saint Barthélemy'));
        Country::create(array('code' => 'BLR', 'label' => 'Belarus'));
        Country::create(array('code' => 'BLZ', 'label' => 'Belize'));
        Country::create(array('code' => 'BMU', 'label' => 'Bermuda'));
        Country::create(array('code' => 'BOL', 'label' => 'Bolivia, Plurinational State of'));
        Country::create(array('code' => 'BRA', 'label' => 'Brazil'));
        Country::create(array('code' => 'BRB', 'label' => 'Barbados'));
        Country::create(array('code' => 'BRN', 'label' => 'Brunei Darussalam'));
        Country::create(array('code' => 'BTN', 'label' => 'Bhutan'));
        Country::create(array('code' => 'BVT', 'label' => 'Bouvet Island'));
        Country::create(array('code' => 'BWA', 'label' => 'Botswana'));
        Country::create(array('code' => 'CAF', 'label' => 'Central African Republic'));
        Country::create(array('code' => 'CAN', 'label' => 'Canada'));
        Country::create(array('code' => 'CCK', 'label' => 'Cocos (Keeling) Islands'));
        Country::create(array('code' => 'CHE', 'label' => 'Switzerland'));
        Country::create(array('code' => 'CHL', 'label' => 'Chile'));
        Country::create(array('code' => 'CHN', 'label' => 'China'));
        Country::create(array('code' => 'CIV', 'label' => 'Côte d\'Ivoire'));
        Country::create(array('code' => 'CMR', 'label' => 'Cameroon'));
        Country::create(array('code' => 'COD', 'label' => 'Congo, the Democratic Republic of the'));
        Country::create(array('code' => 'COG', 'label' => 'Congo'));
        Country::create(array('code' => 'COK', 'label' => 'Cook Islands'));
        Country::create(array('code' => 'COL', 'label' => 'Colombia'));
        Country::create(array('code' => 'COM', 'label' => 'Comoros'));
        Country::create(array('code' => 'CPV', 'label' => 'Cape Verde'));
        Country::create(array('code' => 'CRI', 'label' => 'Costa Rica'));
        Country::create(array('code' => 'CUB', 'label' => 'Cuba'));
        Country::create(array('code' => 'CUW', 'label' => 'Curaçao'));
        Country::create(array('code' => 'CXR', 'label' => 'Christmas Island'));
        Country::create(array('code' => 'CYM', 'label' => 'Cayman Islands'));
        Country::create(array('code' => 'CYP', 'label' => 'Cyprus'));
        Country::create(array('code' => 'CZE', 'label' => 'Czech Republic'));
        Country::create(array('code' => 'DEU', 'label' => 'Germany'));
        Country::create(array('code' => 'DJI', 'label' => 'Djibouti'));
        Country::create(array('code' => 'DMA', 'label' => 'Dominica'));
        Country::create(array('code' => 'DNK', 'label' => 'Denmark'));
        Country::create(array('code' => 'DOM', 'label' => 'Dominican Republic'));
        Country::create(array('code' => 'DZA', 'label' => 'Algeria'));
        Country::create(array('code' => 'ECU', 'label' => 'Ecuador'));
        Country::create(array('code' => 'EGY', 'label' => 'Egypt'));
        Country::create(array('code' => 'ERI', 'label' => 'Eritrea'));
        Country::create(array('code' => 'ESH', 'label' => 'Western Sahara'));
        Country::create(array('code' => 'ESP', 'label' => 'Spain'));
        Country::create(array('code' => 'EST', 'label' => 'Estonia'));
        Country::create(array('code' => 'ETH', 'label' => 'Ethiopia'));
        Country::create(array('code' => 'FIN', 'label' => 'Finland'));
        Country::create(array('code' => 'FJI', 'label' => 'Fiji'));
        Country::create(array('code' => 'FLK', 'label' => 'Falkland Islands (Malvinas)'));
        Country::create(array('code' => 'FRA', 'label' => 'France'));
        Country::create(array('code' => 'FRO', 'label' => 'Faroe Islands'));
        Country::create(array('code' => 'FSM', 'label' => 'Micronesia, Federated States of'));
        Country::create(array('code' => 'GAB', 'label' => 'Gabon'));
        Country::create(array('code' => 'GBR', 'label' => 'United Kingdom'));
        Country::create(array('code' => 'GEO', 'label' => 'Georgia'));
        Country::create(array('code' => 'GGY', 'label' => 'Guernsey'));
        Country::create(array('code' => 'GHA', 'label' => 'Ghana'));
        Country::create(array('code' => 'GIB', 'label' => 'Gibraltar'));
        Country::create(array('code' => 'GIN', 'label' => 'Guinea'));
        Country::create(array('code' => 'GLP', 'label' => 'Guadeloupe'));
        Country::create(array('code' => 'GMB', 'label' => 'Gambia'));
        Country::create(array('code' => 'GNB', 'label' => 'Guinea-Bissau'));
        Country::create(array('code' => 'GNQ', 'label' => 'Equatorial Guinea'));
        Country::create(array('code' => 'GRC', 'label' => 'Greece'));
        Country::create(array('code' => 'GRD', 'label' => 'Grenada'));
        Country::create(array('code' => 'GRL', 'label' => 'Greenland'));
        Country::create(array('code' => 'GTM', 'label' => 'Guatemala'));
        Country::create(array('code' => 'GUF', 'label' => 'French Guiana'));
        Country::create(array('code' => 'GUM', 'label' => 'Guam'));
        Country::create(array('code' => 'GUY', 'label' => 'Guyana'));
        Country::create(array('code' => 'HKG', 'label' => 'Hong Kong'));
        Country::create(array('code' => 'HMD', 'label' => 'Heard Island and McDonald Islands'));
        Country::create(array('code' => 'HND', 'label' => 'Honduras'));
        Country::create(array('code' => 'HRV', 'label' => 'Croatia'));
        Country::create(array('code' => 'HTI', 'label' => 'Haiti'));
        Country::create(array('code' => 'HUN', 'label' => 'Hungary'));
        Country::create(array('code' => 'IDN', 'label' => 'Indonesia'));
        Country::create(array('code' => 'IMN', 'label' => 'Isle of Man'));
        Country::create(array('code' => 'IND', 'label' => 'India'));
        Country::create(array('code' => 'IOT', 'label' => 'British Indian Ocean Territory'));
        Country::create(array('code' => 'IRL', 'label' => 'Ireland'));
        Country::create(array('code' => 'IRN', 'label' => 'Iran, Islamic Republic of'));
        Country::create(array('code' => 'IRQ', 'label' => 'Iraq'));
        Country::create(array('code' => 'ISL', 'label' => 'Iceland'));
        Country::create(array('code' => 'ISR', 'label' => 'Israel'));
        Country::create(array('code' => 'ITA', 'label' => 'Italy'));
        Country::create(array('code' => 'JAM', 'label' => 'Jamaica'));
        Country::create(array('code' => 'JEY', 'label' => 'Jersey'));
        Country::create(array('code' => 'JOR', 'label' => 'Jordan'));
        Country::create(array('code' => 'JPN', 'label' => 'Japan'));
        Country::create(array('code' => 'KAZ', 'label' => 'Kazakhstan'));
        Country::create(array('code' => 'KEN', 'label' => 'Kenya'));
        Country::create(array('code' => 'KGZ', 'label' => 'Kyrgyzstan'));
        Country::create(array('code' => 'KHM', 'label' => 'Cambodia'));
        Country::create(array('code' => 'KIR', 'label' => 'Kiribati'));
        Country::create(array('code' => 'KNA', 'label' => 'Saint Kitts and Nevis'));
        Country::create(array('code' => 'KOR', 'label' => 'Korea, Republic of'));
        Country::create(array('code' => 'KWT', 'label' => 'Kuwait'));
        Country::create(array('code' => 'LAO', 'label' => 'Lao People\'s Democratic Republic'));
        Country::create(array('code' => 'LBN', 'label' => 'Lebanon'));
        Country::create(array('code' => 'LBR', 'label' => 'Liberia'));
        Country::create(array('code' => 'LBY', 'label' => 'Libya'));
        Country::create(array('code' => 'LCA', 'label' => 'Saint Lucia'));
        Country::create(array('code' => 'LIE', 'label' => 'Liechtenstein'));
        Country::create(array('code' => 'LKA', 'label' => 'Sri Lanka'));
        Country::create(array('code' => 'LSO', 'label' => 'Lesotho'));
        Country::create(array('code' => 'LTU', 'label' => 'Lithuania'));
        Country::create(array('code' => 'LUX', 'label' => 'Luxembourg'));
        Country::create(array('code' => 'LVA', 'label' => 'Latvia'));
        Country::create(array('code' => 'MAC', 'label' => 'Macao'));
        Country::create(array('code' => 'MAF', 'label' => 'Saint Martin (French part)'));
        Country::create(array('code' => 'MAR', 'label' => 'Morocco'));
        Country::create(array('code' => 'MCO', 'label' => 'Monaco'));
        Country::create(array('code' => 'MDA', 'label' => 'Moldova, Republic of'));
        Country::create(array('code' => 'MDG', 'label' => 'Madagascar'));
        Country::create(array('code' => 'MDV', 'label' => 'Maldives'));
        Country::create(array('code' => 'MEX', 'label' => 'Mexico'));
        Country::create(array('code' => 'MHL', 'label' => 'Marshall Islands'));
        Country::create(array('code' => 'MKD', 'label' => 'Macedonia, the former Yugoslav Republic of'));
        Country::create(array('code' => 'MLI', 'label' => 'Mali'));
        Country::create(array('code' => 'MLT', 'label' => 'Malta'));
        Country::create(array('code' => 'MMR', 'label' => 'Myanmar'));
        Country::create(array('code' => 'MNE', 'label' => 'Montenegro'));
        Country::create(array('code' => 'MNG', 'label' => 'Mongolia'));
        Country::create(array('code' => 'MNP', 'label' => 'Northern Mariana Islands'));
        Country::create(array('code' => 'MOZ', 'label' => 'Mozambique'));
        Country::create(array('code' => 'MRT', 'label' => 'Mauritania'));
        Country::create(array('code' => 'MSR', 'label' => 'Montserrat'));
        Country::create(array('code' => 'MTQ', 'label' => 'Martinique'));
        Country::create(array('code' => 'MUS', 'label' => 'Mauritius'));
        Country::create(array('code' => 'MWI', 'label' => 'Malawi'));
        Country::create(array('code' => 'MYS', 'label' => 'Malaysia'));
        Country::create(array('code' => 'MYT', 'label' => 'Mayotte'));
        Country::create(array('code' => 'NAM', 'label' => 'Namibia'));
        Country::create(array('code' => 'NCL', 'label' => 'New Caledonia'));
        Country::create(array('code' => 'NER', 'label' => 'Niger'));
        Country::create(array('code' => 'NFK', 'label' => 'Norfolk Island'));
        Country::create(array('code' => 'NGA', 'label' => 'Nigeria'));
        Country::create(array('code' => 'NIC', 'label' => 'Nicaragua'));
        Country::create(array('code' => 'NIU', 'label' => 'Niue'));
        Country::create(array('code' => 'NLD', 'label' => 'Netherlands'));
        Country::create(array('code' => 'NOR', 'label' => 'Norway'));
        Country::create(array('code' => 'NPL', 'label' => 'Nepal'));
        Country::create(array('code' => 'NRU', 'label' => 'Nauru'));
        Country::create(array('code' => 'NZL', 'label' => 'New Zealand'));
        Country::create(array('code' => 'OMN', 'label' => 'Oman'));
        Country::create(array('code' => 'PAK', 'label' => 'Pakistan'));
        Country::create(array('code' => 'PAN', 'label' => 'Panama'));
        Country::create(array('code' => 'PCN', 'label' => 'Pitcairn'));
        Country::create(array('code' => 'PER', 'label' => 'Peru'));
        Country::create(array('code' => 'PHL', 'label' => 'Philippines'));
        Country::create(array('code' => 'PLW', 'label' => 'Palau'));
        Country::create(array('code' => 'PNG', 'label' => 'Papua New Guinea'));
        Country::create(array('code' => 'POL', 'label' => 'Poland'));
        Country::create(array('code' => 'PRI', 'label' => 'Puerto Rico'));
        Country::create(array('code' => 'PRK', 'label' => 'Korea, Democratic People\'s Republic of'));
        Country::create(array('code' => 'PRT', 'label' => 'Portugal'));
        Country::create(array('code' => 'PRY', 'label' => 'Paraguay'));
        Country::create(array('code' => 'PSE', 'label' => 'Palestine, State of'));
        Country::create(array('code' => 'PYF', 'label' => 'French Polynesia'));
        Country::create(array('code' => 'QAT', 'label' => 'Qatar'));
        Country::create(array('code' => 'REU', 'label' => 'Réunion'));
        Country::create(array('code' => 'ROU', 'label' => 'Romania'));
        Country::create(array('code' => 'RUS', 'label' => 'Russian Federation'));
        Country::create(array('code' => 'RWA', 'label' => 'Rwanda'));
        Country::create(array('code' => 'SAU', 'label' => 'Saudi Arabia'));
        Country::create(array('code' => 'SDN', 'label' => 'Sudan'));
        Country::create(array('code' => 'SEN', 'label' => 'Senegal'));
        Country::create(array('code' => 'SGP', 'label' => 'Singapore'));
        Country::create(array('code' => 'SGS', 'label' => 'South Georgia and the South Sandwich Islands'));
        Country::create(array('code' => 'SHN', 'label' => 'Saint Helena, Ascension and Tristan da Cunha'));
        Country::create(array('code' => 'SJM', 'label' => 'Svalbard and Jan Mayen'));
        Country::create(array('code' => 'SLB', 'label' => 'Solomon Islands'));
        Country::create(array('code' => 'SLE', 'label' => 'Sierra Leone'));
        Country::create(array('code' => 'SLV', 'label' => 'El Salvador'));
        Country::create(array('code' => 'SMR', 'label' => 'San Marino'));
        Country::create(array('code' => 'SOM', 'label' => 'Somalia'));
        Country::create(array('code' => 'SPM', 'label' => 'Saint Pierre and Miquelon'));
        Country::create(array('code' => 'SRB', 'label' => 'Serbia'));
        Country::create(array('code' => 'SSD', 'label' => 'South Sudan'));
        Country::create(array('code' => 'STP', 'label' => 'Sao Tome and Principe'));
        Country::create(array('code' => 'SUR', 'label' => 'Suriname'));
        Country::create(array('code' => 'SVK', 'label' => 'Slovakia'));
        Country::create(array('code' => 'SVN', 'label' => 'Slovenia'));
        Country::create(array('code' => 'SWE', 'label' => 'Sweden'));
        Country::create(array('code' => 'SWZ', 'label' => 'Swaziland'));
        Country::create(array('code' => 'SXM', 'label' => 'Sint Maarten (Dutch part)'));
        Country::create(array('code' => 'SYC', 'label' => 'Seychelles'));
        Country::create(array('code' => 'SYR', 'label' => 'Syrian Arab Republic'));
        Country::create(array('code' => 'TCA', 'label' => 'Turks and Caicos Islands'));
        Country::create(array('code' => 'TCD', 'label' => 'Chad'));
        Country::create(array('code' => 'TGO', 'label' => 'Togo'));
        Country::create(array('code' => 'THA', 'label' => 'Thailand'));
        Country::create(array('code' => 'TJK', 'label' => 'Tajikistan'));
        Country::create(array('code' => 'TKL', 'label' => 'Tokelau'));
        Country::create(array('code' => 'TKM', 'label' => 'Turkmenistan'));
        Country::create(array('code' => 'TLS', 'label' => 'Timor-Leste'));
        Country::create(array('code' => 'TON', 'label' => 'Tonga'));
        Country::create(array('code' => 'TTO', 'label' => 'Trinidad and Tobago'));
        Country::create(array('code' => 'TUN', 'label' => 'Tunisia'));
        Country::create(array('code' => 'TUR', 'label' => 'Turkey'));
        Country::create(array('code' => 'TUV', 'label' => 'Tuvalu'));
        Country::create(array('code' => 'TWN', 'label' => 'Taiwan, Province of China'));
        Country::create(array('code' => 'TZA', 'label' => 'Tanzania, United Republic of'));
        Country::create(array('code' => 'UGA', 'label' => 'Uganda'));
        Country::create(array('code' => 'UKR', 'label' => 'Ukraine'));
        Country::create(array('code' => 'UMI', 'label' => 'United States Minor Outlying Islands'));
        Country::create(array('code' => 'URY', 'label' => 'Uruguay'));
        Country::create(array('code' => 'USA', 'label' => 'United States'));
        Country::create(array('code' => 'UZB', 'label' => 'Uzbekistan'));
        Country::create(array('code' => 'VAT', 'label' => 'Holy See (Vatican City State)'));
        Country::create(array('code' => 'VCT', 'label' => 'Saint Vincent and the Grenadines'));
        Country::create(array('code' => 'VEN', 'label' => 'Venezuela, Bolivarian Republic of'));
        Country::create(array('code' => 'VGB', 'label' => 'Virgin Islands, British'));
        Country::create(array('code' => 'VIR', 'label' => 'Virgin Islands, U.S.'));
        Country::create(array('code' => 'VNM', 'label' => 'Viet Nam'));
        Country::create(array('code' => 'VUT', 'label' => 'Vanuatu'));
        Country::create(array('code' => 'WLF', 'label' => 'Wallis and Futuna'));
        Country::create(array('code' => 'WSM', 'label' => 'Samoa'));
        Country::create(array('code' => 'YEM', 'label' => 'Yemen'));
        Country::create(array('code' => 'ZAF', 'label' => 'South Africa'));
        Country::create(array('code' => 'ZMB', 'label' => 'Zambia'));
        Country::create(array('code' => 'ZWE', 'label' => 'Zimbabwe'));

    }
}