<?php

class CurrencyTableSeeder extends Seeder {

      public function run(){

            DB::table('currency')->delete();

            Currency::create(array('code' => 'AED', 'label' => 'United Arab Emirates Dirham'));
            Currency::create(array('code' => 'AFN', 'label' => 'Afghanistan Afghani'));
            Currency::create(array('code' => 'ALL', 'label' => 'Albania Lek'));
            Currency::create(array('code' => 'AMD', 'label' => 'Armenia Dram'));
            Currency::create(array('code' => 'ANG', 'label' => 'Netherlands Antilles Guilder'));
            Currency::create(array('code' => 'AOA', 'label' => 'Angola Kwanza'));
            Currency::create(array('code' => 'ARS', 'label' => 'Argentina Peso'));
            Currency::create(array('code' => 'AUD', 'label' => 'Australia Dollar'));
            Currency::create(array('code' => 'AWG', 'label' => 'Aruba Guilder'));
            Currency::create(array('code' => 'AZN', 'label' => 'Azerbaijan New Manat'));
            Currency::create(array('code' => 'BAM', 'label' => 'Bosnia and Herzegovina Convertible Marka'));
            Currency::create(array('code' => 'BBD', 'label' => 'Barbados Dollar'));
            Currency::create(array('code' => 'BDT', 'label' => 'Bangladesh Taka'));
            Currency::create(array('code' => 'BGN', 'label' => 'Bulgaria Lev'));
            Currency::create(array('code' => 'BHD', 'label' => 'Bahrain Dinar'));
            Currency::create(array('code' => 'BIF', 'label' => 'Burundi Franc'));
            Currency::create(array('code' => 'BMD', 'label' => 'Bermuda Dollar'));
            Currency::create(array('code' => 'BND', 'label' => 'Brunei Darussalam Dollar'));
            Currency::create(array('code' => 'BOB', 'label' => 'Bolivia Boliviano'));
            Currency::create(array('code' => 'BRL', 'label' => 'Brazil Real'));
            Currency::create(array('code' => 'BSD', 'label' => 'Bahamas Dollar'));
            Currency::create(array('code' => 'BTN', 'label' => 'Bhutan Ngultrum'));
            Currency::create(array('code' => 'BWP', 'label' => 'Botswana Pula'));
            Currency::create(array('code' => 'BYR', 'label' => 'Belarus Ruble'));
            Currency::create(array('code' => 'BZD', 'label' => 'Belize Dollar'));
            Currency::create(array('code' => 'CAD', 'label' => 'Canada Dollar'));
            Currency::create(array('code' => 'CDF', 'label' => 'Congo/Kinshasa Franc'));
            Currency::create(array('code' => 'CHF', 'label' => 'Switzerland Franc'));
            Currency::create(array('code' => 'CLP', 'label' => 'Chile Peso'));
            Currency::create(array('code' => 'CNY', 'label' => 'China Yuan Renminbi'));
            Currency::create(array('code' => 'COP', 'label' => 'Colombia Peso'));
            Currency::create(array('code' => 'CRC', 'label' => 'Costa Rica Colon'));
            Currency::create(array('code' => 'CUC', 'label' => 'Cuba Convertible Peso'));
            Currency::create(array('code' => 'CUP', 'label' => 'Cuba Peso'));
            Currency::create(array('code' => 'CVE', 'label' => 'Cape Verde Escudo'));
            Currency::create(array('code' => 'CZK', 'label' => 'Czech Republic Koruna'));
            Currency::create(array('code' => 'DJF', 'label' => 'Djibouti Franc'));
            Currency::create(array('code' => 'DKK', 'label' => 'Denmark Krone'));
            Currency::create(array('code' => 'DOP', 'label' => 'Dominican Republic Peso'));
            Currency::create(array('code' => 'DZD', 'label' => 'Algeria Dinar'));
            Currency::create(array('code' => 'EGP', 'label' => 'Egypt Pound'));
            Currency::create(array('code' => 'ERN', 'label' => 'Eritrea Nakfa'));
            Currency::create(array('code' => 'ETB', 'label' => 'Ethiopia Birr'));
            Currency::create(array('code' => 'EUR', 'label' => 'Euro Member Countries'));
            Currency::create(array('code' => 'FJD', 'label' => 'Fiji Dollar'));
            Currency::create(array('code' => 'FKP', 'label' => 'Falkland Islands (Malvinas) Pound'));
            Currency::create(array('code' => 'GBP', 'label' => 'United Kingdom Pound'));
            Currency::create(array('code' => 'GEL', 'label' => 'Georgia Lari'));
            Currency::create(array('code' => 'GGP', 'label' => 'Guernsey Pound'));
            Currency::create(array('code' => 'GHS', 'label' => 'Ghana Cedi'));
            Currency::create(array('code' => 'GIP', 'label' => 'Gibraltar Pound'));
            Currency::create(array('code' => 'GMD', 'label' => 'Gambia Dalasi'));
            Currency::create(array('code' => 'GNF', 'label' => 'Guinea Franc'));
            Currency::create(array('code' => 'GTQ', 'label' => 'Guatemala Quetzal'));
            Currency::create(array('code' => 'GYD', 'label' => 'Guyana Dollar'));
            Currency::create(array('code' => 'HKD', 'label' => 'Hong Kong Dollar'));
            Currency::create(array('code' => 'HNL', 'label' => 'Honduras Lempira'));
            Currency::create(array('code' => 'HRK', 'label' => 'Croatia Kuna'));
            Currency::create(array('code' => 'HTG', 'label' => 'Haiti Gourde'));
            Currency::create(array('code' => 'HUF', 'label' => 'Hungary Forint'));
            Currency::create(array('code' => 'IDR', 'label' => 'Indonesia Rupiah'));
            Currency::create(array('code' => 'ILS', 'label' => 'Israel Shekel'));
            Currency::create(array('code' => 'IMP', 'label' => 'Isle of Man Pound'));
            Currency::create(array('code' => 'INR', 'label' => 'India Rupee'));
            Currency::create(array('code' => 'IQD', 'label' => 'Iraq Dinar'));
            Currency::create(array('code' => 'IRR', 'label' => 'Iran Rial'));
            Currency::create(array('code' => 'ISK', 'label' => 'Iceland Krona'));
            Currency::create(array('code' => 'JEP', 'label' => 'Jersey Pound'));
            Currency::create(array('code' => 'JMD', 'label' => 'Jamaica Dollar'));
            Currency::create(array('code' => 'JOD', 'label' => 'Jordan Dinar'));
            Currency::create(array('code' => 'JPY', 'label' => 'Japan Yen'));
            Currency::create(array('code' => 'KES', 'label' => 'Kenya Shilling'));
            Currency::create(array('code' => 'KGS', 'label' => 'Kyrgyzstan Som'));
            Currency::create(array('code' => 'KHR', 'label' => 'Cambodia Riel'));
            Currency::create(array('code' => 'KMF', 'label' => 'Comoros Franc'));
            Currency::create(array('code' => 'KPW', 'label' => 'Korea (North) Won'));
            Currency::create(array('code' => 'KRW', 'label' => 'Korea (South) Won'));
            Currency::create(array('code' => 'KWD', 'label' => 'Kuwait Dinar'));
            Currency::create(array('code' => 'KYD', 'label' => 'Cayman Islands Dollar'));
            Currency::create(array('code' => 'KZT', 'label' => 'Kazakhstan Tenge'));
            Currency::create(array('code' => 'LAK', 'label' => 'Laos Kip'));
            Currency::create(array('code' => 'LBP', 'label' => 'Lebanon Pound'));
            Currency::create(array('code' => 'LKR', 'label' => 'Sri Lanka Rupee'));
            Currency::create(array('code' => 'LRD', 'label' => 'Liberia Dollar'));
            Currency::create(array('code' => 'LSL', 'label' => 'Lesotho Loti'));
            Currency::create(array('code' => 'LTL', 'label' => 'Lithuania Litas'));
            Currency::create(array('code' => 'LVL', 'label' => 'Latvia Lat'));
            Currency::create(array('code' => 'LYD', 'label' => 'Libya Dinar'));
            Currency::create(array('code' => 'MAD', 'label' => 'Morocco Dirham'));
            Currency::create(array('code' => 'MDL', 'label' => 'Moldova Leu'));
            Currency::create(array('code' => 'MGA', 'label' => 'Madagascar Ariary'));
            Currency::create(array('code' => 'MKD', 'label' => 'Macedonia Denar'));
            Currency::create(array('code' => 'MMK', 'label' => 'Myanmar (Burma) Kyat'));
            Currency::create(array('code' => 'MNT', 'label' => 'Mongolia Tughrik'));
            Currency::create(array('code' => 'MOP', 'label' => 'Macau Pataca'));
            Currency::create(array('code' => 'MRO', 'label' => 'Mauritania Ouguiya'));
            Currency::create(array('code' => 'MUR', 'label' => 'Mauritius Rupee'));
            Currency::create(array('code' => 'MVR', 'label' => 'Maldives (Maldive Islands) Rufiyaa'));
            Currency::create(array('code' => 'MWK', 'label' => 'Malawi Kwacha'));
            Currency::create(array('code' => 'MXN', 'label' => 'Mexico Peso'));
            Currency::create(array('code' => 'MYR', 'label' => 'Malaysia Ringgit'));
            Currency::create(array('code' => 'MZN', 'label' => 'Mozambique Metical'));
            Currency::create(array('code' => 'NAD', 'label' => 'Namibia Dollar'));
            Currency::create(array('code' => 'NGN', 'label' => 'Nigeria Naira'));
            Currency::create(array('code' => 'NIO', 'label' => 'Nicaragua Cordoba'));
            Currency::create(array('code' => 'NOK', 'label' => 'Norway Krone'));
            Currency::create(array('code' => 'NPR', 'label' => 'Nepal Rupee'));
            Currency::create(array('code' => 'NZD', 'label' => 'New Zealand Dollar'));
            Currency::create(array('code' => 'OMR', 'label' => 'Oman Rial'));
            Currency::create(array('code' => 'PAB', 'label' => 'Panama Balboa'));
            Currency::create(array('code' => 'PEN', 'label' => 'Peru Nuevo Sol'));
            Currency::create(array('code' => 'PGK', 'label' => 'Papua New Guinea Kina'));
            Currency::create(array('code' => 'PHP', 'label' => 'Philippines Peso'));
            Currency::create(array('code' => 'PKR', 'label' => 'Pakistan Rupee'));
            Currency::create(array('code' => 'PLN', 'label' => 'Poland Zloty'));
            Currency::create(array('code' => 'PYG', 'label' => 'Paraguay Guarani'));
            Currency::create(array('code' => 'QAR', 'label' => 'Qatar Riyal'));
            Currency::create(array('code' => 'RON', 'label' => 'Romania New Leu'));
            Currency::create(array('code' => 'RSD', 'label' => 'Serbia Dinar'));
            Currency::create(array('code' => 'RUB', 'label' => 'Russia Ruble'));
            Currency::create(array('code' => 'RWF', 'label' => 'Rwanda Franc'));
            Currency::create(array('code' => 'SAR', 'label' => 'Saudi Arabia Riyal'));
            Currency::create(array('code' => 'SBD', 'label' => 'Solomon Islands Dollar'));
            Currency::create(array('code' => 'SCR', 'label' => 'Seychelles Rupee'));
            Currency::create(array('code' => 'SDG', 'label' => 'Sudan Pound'));
            Currency::create(array('code' => 'SEK', 'label' => 'Sweden Krona'));
            Currency::create(array('code' => 'SGD', 'label' => 'Singapore Dollar'));
            Currency::create(array('code' => 'SHP', 'label' => 'Saint Helena Pound'));
            Currency::create(array('code' => 'SLL', 'label' => 'Sierra Leone Leone'));
            Currency::create(array('code' => 'SOS', 'label' => 'Somalia Shilling'));
            Currency::create(array('code' => 'SPL*', 'label' => 'Seborga Luigino'));
            Currency::create(array('code' => 'SRD', 'label' => 'Suriname Dollar'));
            Currency::create(array('code' => 'STD', 'label' => 'São Tomé and Príncipe Dobra'));
            Currency::create(array('code' => 'SVC', 'label' => 'El Salvador Colon'));
            Currency::create(array('code' => 'SYP', 'label' => 'Syria Pound'));
            Currency::create(array('code' => 'SZL', 'label' => 'Swaziland Lilangeni'));
            Currency::create(array('code' => 'THB', 'label' => 'Thailand Baht'));
            Currency::create(array('code' => 'TJS', 'label' => 'Tajikistan Somoni'));
            Currency::create(array('code' => 'TMT', 'label' => 'Turkmenistan Manat'));
            Currency::create(array('code' => 'TND', 'label' => 'Tunisia Dinar'));
            Currency::create(array('code' => 'TOP', 'label' => 'Tonga Pa\'anga'));
            Currency::create(array('code' => 'TRY', 'label' => 'Turkey Lira'));
            Currency::create(array('code' => 'TTD', 'label' => 'Trinidad and Tobago Dollar'));
            Currency::create(array('code' => 'TVD', 'label' => 'Tuvalu Dollar'));
            Currency::create(array('code' => 'TWD', 'label' => 'Taiwan New Dollar'));
            Currency::create(array('code' => 'TZS', 'label' => 'Tanzania Shilling'));
            Currency::create(array('code' => 'UAH', 'label' => 'Ukraine Hryvna'));
            Currency::create(array('code' => 'UGX', 'label' => 'Uganda Shilling'));
            Currency::create(array('code' => 'USD', 'label' => 'United States Dollar'));
            Currency::create(array('code' => 'UYU', 'label' => 'Uruguay Peso'));
            Currency::create(array('code' => 'UZS', 'label' => 'Uzbekistan Som'));
            Currency::create(array('code' => 'VEF', 'label' => 'Venezuela Bolivar'));
            Currency::create(array('code' => 'VND', 'label' => 'Viet Nam Dong'));
            Currency::create(array('code' => 'VUV', 'label' => 'Vanuatu Vatu'));
            Currency::create(array('code' => 'WST', 'label' => 'Samoa Tala'));
            Currency::create(array('code' => 'XAF', 'label' => 'Communauté Financière Africaine (BEAC) CFA Franc BEAC'));
            Currency::create(array('code' => 'XCD', 'label' => 'East Caribbean Dollar'));
            Currency::create(array('code' => 'XDR', 'label' => 'International Monetary Fund (IMF) Special Drawing Rights'));
            Currency::create(array('code' => 'XOF', 'label' => 'Communauté Financière Africaine (BCEAO) Franc'));
            Currency::create(array('code' => 'XPF', 'label' => 'Comptoirs Français du Pacifique (CFP) Franc'));
            Currency::create(array('code' => 'YER', 'label' => 'Yemen Rial'));
            Currency::create(array('code' => 'ZAR', 'label' => 'South Africa Rand'));
            Currency::create(array('code' => 'ZMW', 'label' => 'Zambia Kwacha'));
            Currency::create(array('code' => 'ZWD', 'label' => 'Zimbabwe Dollar'));

    }
}
